services:
  - docker

before_install:
  - docker build -t fib-calc-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fib-calc-test npm test

after_success:
  - docker build -t fib-calc-client ./client
  - docker build -t fib-calc-nginx ./nginx
  - docker build -t fib-calc-server ./server
  - docker build -t fib-calc-worker ./worker
  # login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to dockerhub
  - docker push fib-calc-client
  - docker push fib-calc-nginx
  - docker push fib-calc-server
  - docker push fib-calc-worker


deploy:
  provider: elasticbeanstalk
  region: europe
  app: fib-calc-docker
  env: fib-calc-docker-env
  bucket_name: elasticbeanstalk-bucker-name
  bucket_path: fib-calc
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

